USE cs194;

LOAD DATA LOCAL INFILE 'badges.xml.dat' INTO TABLE badges FIELDS TERMINATED BY '' LINES TERMINATED BY '';
LOAD DATA LOCAL INFILE 'comments.xml.dat' INTO TABLE comments FIELDS TERMINATED BY '' LINES TERMINATED BY '';
LOAD DATA LOCAL INFILE 'users.xml.dat' INTO TABLE users FIELDS TERMINATED BY '' LINES TERMINATED BY '';
LOAD DATA LOCAL INFILE 'questions.xml.dat' INTO TABLE questions FIELDS TERMINATED BY '' LINES TERMINATED BY '';
LOAD DATA LOCAL INFILE 'answers.xml.dat' INTO TABLE answers FIELDS TERMINATED BY '' LINES TERMINATED BY '';
LOAD DATA LOCAL INFILE 'votes.xml.dat' INTO TABLE votes FIELDS TERMINATED BY '' LINES TERMINATED BY '';
