FIELD_KEYS = {
    "badges.xml": ["Date", 
                   "UserId",
                   "Id",
                   "Name"],
    "comments.xml": ["CreationDate", 
                     "Text", 
                     "UserId", 
                     "Score", 
                     "PostId", 
                     "Id"],
    "questions.xml": ["Body", 
                      "ViewCount", 
                      "LastActivityDate", 
                      "Title", 
                      "LastEditorUserId",
                      "LastEditorDisplayName",
                      "LastEditDateTime",
                      "CommentCount",
                      "AnswerCount",
                      "AcceptedAnswerId",
                      "Score",
                      "PostTypeId",
                      "OwnerUserId",
                      "Tags",
                      "CreationDate",
                      "FavoriteCount",
                      "Id"],
    "answers.xml": ["Body", 
                    "ViewCount", 
                    "LastEditorDisplayName",
                    "LastEditorUserId",
                    "PostTypeId",
                    "LastEditDate",
                    "CommentCount",
                    "Score",
                    "ParentId",
                    "OwnerUserId",
                    "CreationDate",
                    "Id"
                    "LastActivityDate"],
    "users.xml": ["DownVotes",
                  "DisplayName",
                  "Views",
                  "AboutMe",
                  "LastAccessDate",
                  "WebsiteUrl",
                  "EmailHash",
                  "Reputation",
                  "Location",
                  "UpVotes",
                  "CreationDate",
                  "Id"],
    "votes.xml": ["VoteTypeId",
                  "PostId",
                  "Id",
                  "CreationDate"]
}
